const lessons=[{id:'1-1',chapter:'第1章：今の状況を整理する',title:'現在地を正しく把握する',type:'video',done:true},{id:'1-2',chapter:'第1章：今の状況を整理する',title:'別れから今までを振り返る',type:'work',done:true},{id:'2-1',chapter:'第2章：感情を整える',title:'不安や焦りが生まれる仕組み',type:'video',done:true},{id:'2-2',chapter:'第2章：感情を整える',title:'不安が出たときの思考整理',type:'work',done:false},{id:'2-3',chapter:'第2章：感情を整える',title:'相手ではなく自分に意識を戻す',type:'video',done:false},{id:'3-1',chapter:'第3章：行動を整える',title:'今の関係に必要な距離感',type:'video',done:false,locked:true},{id:'3-2',chapter:'第3章：行動を整える',title:'次の期間に取り組むこと',type:'work',done:false,locked:true}];
function login(){const id=document.querySelector('#member-id');const pw=document.querySelector('#password');if(!id.value||!pw.value){document.querySelector('#login-error').textContent='IDとパスワードを入力してください';return}location.href='dashboard.html'}
function renderLessons(){const root=document.querySelector('#lesson-root');if(!root)return;const groups=[...new Set(lessons.map(x=>x.chapter))];root.innerHTML=groups.map(ch=>`<section class="chapter"><div class="chapter-heading">${ch}</div>${lessons.filter(x=>x.chapter===ch).map(x=>`<button class="lesson-card ${x.done?'completed':''} ${x.locked?'locked':''}" ${x.locked?'disabled':''} onclick="openLesson('${x.id}')"><span class="lesson-num">${x.done?'✓':x.locked?'🔒':x.id}</span><span class="lesson-copy"><span class="lesson-type ${x.type}">${x.type==='video'?'動画':'ワーク'}</span><strong>${x.title}</strong>${x.locked?'<small>前のコンテンツを完了すると公開されます</small>':''}</span><span class="lesson-arrow">${x.done?'✓':'›'}</span></button>`).join('')}</section>`).join('')}
function openLesson(id){const l=lessons.find(x=>x.id===id);if(!l||l.locked)return;document.querySelector('#modal-title').textContent=l.title;document.querySelector('#modal-content').innerHTML=l.type==='video'?`<div class="video-box"><span class="play">▶</span><small>YouTube動画がここに表示されます</small></div><button class="wide-btn" onclick="closeModal()">視聴を完了する</button>`:`<div class="work-prompt">今、一番強く感じている不安は何ですか？<br>その不安の奥にある本音も書いてみましょう。</div><label>あなたの回答</label><textarea id="work-answer" placeholder="ここに回答を入力してください">${localStorage.getItem('demo-work')||''}</textarea><button class="wide-btn" onclick="saveWork()">回答を保存する</button>`;document.querySelector('#lesson-modal').classList.add('open')}
function closeModal(){document.querySelector('#lesson-modal')?.classList.remove('open')}
function saveWork(){localStorage.setItem('demo-work',document.querySelector('#work-answer').value);const b=document.querySelector('#modal-content .wide-btn');b.textContent='保存しました ✓'}
const members=[{name:'山田 花子',progress:57,last:'今日 09:18',concern:'返信がないと忘れられてしまう気がして不安です。',flag:'要確認',tone:'danger'},{name:'佐藤 美咲',progress:86,last:'昨日 20:42',concern:'連絡するタイミングを落ち着いて考えています。',flag:'順調',tone:'good'},{name:'高橋 彩',progress:43,last:'5日前',concern:'自分の気持ちをまだ整理しきれていません。',flag:'停滞',tone:'warning'},{name:'伊藤 奈緒',progress:14,last:'8日前',concern:'ワーク回答はまだありません。',flag:'要確認',tone:'danger'}];
function renderAdmin(selected=0){const list=document.querySelector('#member-list');if(!list)return;list.innerHTML=members.map((m,i)=>`<button class="${i===selected?'active':''}" onclick="renderAdmin(${i})"><span class="member-name"><b>${m.name}</b><small>最終取組 ${m.last}</small></span><span class="member-progress"><b>${m.progress}%</b><span class="mini-track"><i style="width:${m.progress}%"></i></span></span><span class="member-concern">${m.concern}</span><span class="flag ${m.tone}">${m.flag}</span></button>`).join('');const m=members[selected];document.querySelector('#detail-name').textContent=m.name;document.querySelector('#detail-flag').className=`flag ${m.tone}`;document.querySelector('#detail-flag').textContent=m.flag;document.querySelector('#detail-concern').textContent=m.concern;document.querySelector('#detail-progress').textContent=`進捗 ${m.progress}% ・ 最終取組 ${m.last}`}
document.addEventListener('DOMContentLoaded',()=>{renderLessons();renderAdmin()});
