const sessions=[];
const lessons=sessions.flatMap(session=>[
  {id:`${session.number}-video`,round:`第${session.number}回`,title:session.videoTitle,type:'video',url:session.videoUrl,done:false},
  {id:`${session.number}-work`,round:`第${session.number}回`,title:session.workTitle,type:'work',prompt:session.workPrompt,done:false}
]);
const memberAccounts=[{id:'001',password:'misaki',name:'ミサキ'}];
function login(){const id=document.querySelector('#member-id').value.trim();const pw=document.querySelector('#password').value;const error=document.querySelector('#login-error');if(!id||!pw){error.textContent='IDとパスワードを入力してください';return}if(id==='000'&&pw==='ziro'){sessionStorage.setItem('demo-role','admin');sessionStorage.removeItem('member-account');location.href='admin.html';return}const member=memberAccounts.find(account=>account.id===id&&account.password===pw);if(!member){error.textContent='IDまたはパスワードが正しくありません';return}sessionStorage.setItem('demo-role','member');sessionStorage.setItem('member-account',JSON.stringify(member));location.href='dashboard.html'}
function guardAdmin(){if(location.pathname.endsWith('/admin.html')&&sessionStorage.getItem('demo-role')!=='admin')location.href='index.html'}
function renderLessons(){const root=document.querySelector('#lesson-root');if(!root)return;if(!lessons.length){root.innerHTML='<section class="card empty-state"><span>▶</span><h2>講義はまだありません</h2><p>動画講義とワークが追加されると、ここに第1回から順番に表示されます。</p></section>';return}const groups=[...new Set(lessons.map(x=>x.round))];root.innerHTML=groups.map(round=>`<section class="chapter"><div class="chapter-heading">${round}</div>${lessons.filter(x=>x.round===round).map((x,index)=>`<button class="lesson-card ${x.done?'completed':''}" onclick="openLesson('${x.id}')"><span class="lesson-num">${x.done?'✓':index+1}</span><span class="lesson-copy"><span class="lesson-type ${x.type}">${x.type==='video'?'動画講義':'ワーク'}</span><strong>${x.title}</strong></span><span class="lesson-arrow">${x.done?'✓':'›'}</span></button>`).join('')}</section>`).join('')}
function openLesson(id){const l=lessons.find(x=>x.id===id);if(!l)return;document.querySelector('#modal-title').textContent=l.title;document.querySelector('#modal-content').innerHTML=l.type==='video'?`<div class="video-box"><span class="play">▶</span><small>動画講義</small></div><button class="wide-btn" onclick="closeModal()">視聴を完了する</button>`:`<div class="work-prompt">${l.prompt}</div><label>あなたの回答</label><textarea id="work-answer" placeholder="ここに回答を入力してください">${localStorage.getItem(`work-${l.id}`)||''}</textarea><button class="wide-btn" onclick="saveWork('${l.id}')">回答を保存する</button>`;document.querySelector('#lesson-modal').classList.add('open')}
function closeModal(){document.querySelector('#lesson-modal')?.classList.remove('open')}
function saveWork(id){localStorage.setItem(`work-${id}`,document.querySelector('#work-answer').value);const b=document.querySelector('#modal-content .wide-btn');b.textContent='保存しました ✓'}
const members=[{name:'ミサキ',progress:0,last:'まだありません',concern:'ワーク回答はまだありません。',flag:'未開始',tone:'warning'}];
function renderAdmin(selected=0){const list=document.querySelector('#member-list');if(!list)return;list.innerHTML=members.map((m,i)=>`<button class="${i===selected?'active':''}" onclick="renderAdmin(${i})"><span class="member-name"><b>${m.name}</b><small>最終取組 ${m.last}</small></span><span class="member-progress"><b>${m.progress}%</b><span class="mini-track"><i style="width:${m.progress}%"></i></span></span><span class="member-concern">${m.concern}</span><span class="flag ${m.tone}">${m.flag}</span></button>`).join('');const m=members[selected];document.querySelector('#detail-name').textContent=m.name;document.querySelector('#detail-flag').className=`flag ${m.tone}`;document.querySelector('#detail-flag').textContent=m.flag;document.querySelector('#detail-concern').textContent=m.concern;document.querySelector('#detail-progress').textContent=`進捗 ${m.progress}% ・ 最終取組 ${m.last}`}
document.addEventListener('keydown',e=>{if(e.key==='Enter'&&document.querySelector('#member-id'))login()});
document.addEventListener('DOMContentLoaded',()=>{guardAdmin();renderLessons();renderAdmin()});
